### ISSUE TITLE
run playground locally

### ISSUE THREAD

**Issue by adai183** [Microsoft/maker.js#215]
I tried serving playground/index.html on a simple node server but it is not functional.
Is there a easy way to run a fully functional playground locally?

**Comment by danmarshall** [comment]
You should be able to run the version from the **gh-pages** branch. That is what is being served on the www page. If you want to run from the **master** or **dev** branch, you can do a "debug" build by running ```tsc``` from the command line. Let me know if that works for you!

**Comment by adai183** [comment]
Thanks!
It works after compiling the typescript.
