### ISSUE TITLE
SVG Optimization 

### ISSUE THREAD

**Issue by villanus** [Microsoft/maker.js#247]
To make for lighter SVG files the number of decimals in SVG result should allow optimization.
Unnecessary groups, class names, white-space and ids should be removed. 
 
 - http://petercollingridge.appspot.com/svg-optimiser  
-  https://github.com/petercollingridge/SVG-optimiser.js
 - https://github.com/svg/svgo

**Comment by villanus** [comment]
Will this work?
function roundPath(path) {
   return path.replace(/[\d\.-][\d\.e-]*/g, function(n){return Math.round(n*10)/10})
}

**Comment by danmarshall** [comment]
Hi @villanus, this has been added to the latest npm package. The default is .001
