### ISSUE TITLE
Ability to set colors per model or layer

### ISSUE THREAD

**Issue by objectiveSee** [Microsoft/maker.js#248]
A common situation for laser cut designs is to have the "cut" lines be red and the "etch" lines to be blue. It would be nice if we could specify multiple colors when exporting to SVG so that we don't have to set the colors manually from another app after rendering the SVG. Setting the color on a model or layer should be adequate.

**Comment by danmarshall** [comment]
This will fit in nicely with an upcoming change I need to make to be able to set other export options by layer.

**Comment by danmarshall** [comment]
FYI there is also color using CSS - not sure if your SVG scenario is web based or not:
https://github.com/Microsoft/maker.js/issues/185

**Comment by objectiveSee** [comment]
Thanks Dan, my scenario is all node based currently, plus I'm terrible with CSS, so I'll just wait on this feature. Luckily I only need to change the color of two layers so it's a simple step in Illustrator.
