### ISSUE TITLE
Update openjscad dependency

### ISSUE THREAD

**Issue by adamdyson** [Microsoft/maker.js#252]
Please update the openjscad dependency from `"@types/openjscad": "0.0.27"` to `"@types/openjscad": "0.0.28"`. Otherwise trying to build the project will fail with messages such as:
```
Error:(11, 24) TS2304:Cannot find name 'Mesh'.
Error:(12, 24) TS2304:Cannot find name 'Mesh'.
Error:(199, 41) TS2694:Namespace '"./node_modules/@types/three/index".THREE' has no exported member 'Object3D'.
```

**Comment by danmarshall** [comment]
Thanks for reporting! Fixed in latest build.
