### ISSUE TITLE
Avoid SVG evenodd rule

### ISSUE THREAD

**Issue by villanus** [Microsoft/maker.js#256]
Illustrator and inkscape do not show evenodd rules until settings are updated.  These settings need to be updated each time a file is opened.
Some cutting software including cutting master for Graphtec also doesnt respect evenodd.

The goal is to avoid the EvenOdd option because for some Plotter software it causes issues. It also causes issues when an SVG is opened up in Adobe Illustrator, until you manually change the file settings to view all paths as even odd.

It turns out that a path can be subtracted from another path:
http://stackoverflow.com/questions/3349651/how-to-achieve-donut-holes-with-paths-in-raphael

Paper.js and Raphael do this by reversing the inner parts.  Does this look like a feasible solution to get rid of Even Odd

Or maybe an option to go through each section of the path, and if DonutHole option is set then subtract the path and set the fill rule to nonzero?

**Comment by danmarshall** [comment]
Well, that took longer than expected, but I'm happy with the results :)
You can now use `{ fillRule: 'nonzero' }` in SVG export to get the reversed winding for inside paths. I need to update the docs accordingly.
