### ISSUE TITLE
Flex section: cloneToBrick

### ISSUE THREAD

**Issue by 3kmch** [Microsoft/maker.js#342]
Is there already a function which helps to add flex sections? At the moment I'm using cloneToBrick which works fine. But from the point of material waste I would like to prevent all unnecessary cuts.  

![beerkini](https://user-images.githubusercontent.com/20172437/42148805-e61a3598-7dd3-11e8-8d45-de96790e9d2a.jpg)

See also https://maker.js.org/playground/?script=https://gist.githubusercontent.com/3kmch/b4568769884592d8253f64c62de5c1f8/raw/4ddd1ddcdaa2d128fa93e3576e9f511129c7d017/beerkini.js

**Comment by danmarshall** [comment]
I'd say keep using cloneToBrick. To clip the paths outside, you can use [makerjs.model.combine](https://maker.js.org/docs/api/modules/makerjs.model.html#combine) with a special combination of flags:

```js
makerjs.model.combine(bottom, wall, true, true, true, false, {trimDeadEnds: false});
```

**Comment by danmarshall** [comment]
just do this prior to calling 
```js
  makerjs.model.combineUnion(bottom, top); // Combine bottom and top
```
so that `bottom` is still a closed geometry.

**Comment by 3kmch** [comment]
Thank you very much Dan, the problem is solved. :)

Feel free to add it to the gallery

https://www.thingiverse.com/thing:2989232
