### ISSUE TITLE
Preselected font

### ISSUE THREAD

**Issue by 3kmch** [Microsoft/maker.js#343]
How can I define a preselected font within the "metaParameters"? I tried different ways but none of them worked.

https://maker.js.org/playground/?script=https://gist.githubusercontent.com/3kmch/511767d5d7d317a579a311280c1f0add/raw/cdaa4e4a8dc6ed623123ad83f4e572e26201e333/foldit.js

![img_20170812_175841](https://user-images.githubusercontent.com/20172437/42419799-0f104fb8-82bc-11e8-9131-f7792feebeca.jpg)

**Comment by danmarshall** [comment]
Hi Kurt,
The font chooser is based on a small hashtag implementation, so for example you could choose all `#stencil` fonts. The tags for each font are here: https://github.com/Microsoft/maker.js/blob/master/fonts/tags.json

Please feel free to add any tags in a PR.

Are you trying to select only a single font? If so, it may defeat the purpose of having a drop-down chooser, if there is only one item to choose.

I can see from your design notes that you want anything *not* tagged with `#stencil`, perhaps we can add a negating operator such as `!` in front of a hash tag.

**Comment by danmarshall** [comment]
Ok, you can now do things like:

* Select all fonts, except those which are stencil:
`* !#stencil`
* Select all stencils that are not serif:
`#stencil !#serif`
* Select union of all stencils and all serifs:
`#stencil #serif`

FYI as of now, we don't have a way to select the intersection of hashtags, e.g. Select *only* those which are stencil serif. I suppose the syntax would be `#stencil#serif` (no space) ? Anyways this is a lot of syntax for a small feature :)

**Comment by danmarshall** [comment]
Oh, btw Kurt - I think this works well with your design: 
`* !#stencil !#connected !#gothic` 👍

**Comment by 3kmch** [comment]
Perfect, that's a elegant solution. :)

https://maker.js.org/playground/?script=https://gist.githubusercontent.com/3kmch/511767d5d7d317a579a311280c1f0add/raw/dd9dd477352bf060bd186c7584ad2d7435edbfad/foldit.js

**Comment by danmarshall** [comment]
This is another cool design, Kurt! How do you specify the perforated lines?

**Comment by 3kmch** [comment]
I'm glad you like it. :)

Our lasercutter has a "Draw Dot" function. So all I need is a vector. Then I can define power and interval and I'm done.

I already tought about adding a checkbox in maker.js, which would replace the standard line by a dotted or dashed line. But I dropped it with the first version.
Would be "Layout on a path" a good approach?

**Comment by danmarshall** [comment]
Yes I'd say [Layout on a path](https://maker.js.org/docs/advanced-drawing/#Layout%20on%20a%20path).
