### ISSUE TITLE
Feature request: Hatch or fill  function

### ISSUE THREAD

**Issue by icodk** [Microsoft/maker.js#372]
Is it possible to draw a filled object 
... and export it to DXF ?
If not natively available, what will it take to simulate it ?
May be on a separate layer with different line thickness or expandingseveral times

**Comment by danmarshall** [comment]
Should be possible with Boolean operations, and some mental gymnastics 🤔 !

Start with your model and a filler model. Let's use a smile and a brick wall:
![image](https://user-images.githubusercontent.com/11507384/47522002-52503300-d849-11e8-851b-4112db8acf71.png)

Then subtract the wall from the smile. (This ruins the smile, we will deal with that afterwards):
![image](https://user-images.githubusercontent.com/11507384/47522143-a1966380-d849-11e8-9aa4-7dbf619d2f33.png)

FYI - here is what the wall looks like by itself: (not a closed geometry)
![image](https://user-images.githubusercontent.com/11507384/47522204-ca1e5d80-d849-11e8-996c-9f6c8177ab8e.png)

So we create a new smile! You can also do this by [cloning](https://maker.js.org/docs/intermediate-drawing/#Cloning) (prior to calling combineSubtraction). Smile1 was a sacrificial model.

![image](https://user-images.githubusercontent.com/11507384/47522403-592b7580-d84a-11e8-8109-bb68418fbcef.png)

Here's sample code:

```js
var m = require('makerjs');
var Smile = require('makerjs-smile');

function hatch() {

	var brick = new m.models.Rectangle(8, 6);
	var wall = m.layout.cloneToBrick(brick, 8, 7, 2);
    m.model.center(wall);
    
	var smile1 = new Smile();
  
    m.model.combineSubtraction(smile1, wall);
  
    var smile2 = new Smile();
	this.models = { wall, smile2 };
  
}

module.exports = hatch;
```
Or [click here to try it now](https://maker.js.org/playground/?script=https://gist.githubusercontent.com/danmarshall/e9a02b4cb8d94625c64fdedd2365f518/raw/382f30f1abd784363d77fa5fb6beb714a63f4a7a/hatch-fill.js)

**Comment by icodk** [comment]
@danmarshall Thanks
Very interesting concept that I might be able to use instead of a solid fill

**Comment by danmarshall** [comment]
Hi @icodk - you've inspired me to create a [separate module to do rasterizing](https://github.com/danmarshall/makerjs-raster).

![image](https://user-images.githubusercontent.com/11507384/47597920-68ddb380-d949-11e8-8ea3-28ffe6a71a7a.png)

[Here is a demo](https://maker.js.org/playground/?script=raster-smile) where you can refine the distance between the lines.

See [this line](https://github.com/danmarshall/makerjs-raster/blob/master/index.ts#L9) for the API; it will do the cloning for you, and return a model of horizontal lines.

**Comment by icodk** [comment]
looks great
Thanks

**Comment by icodk** [comment]
A small optimization could be to check if the object  width is greater then height and to fill accordingly, in order to minimize number of path
