### ISSUE TITLE
[DXF export] What is the best approach to generate a QR model from SVG QR Code

### ISSUE THREAD

**Issue by tkinte** [Microsoft/maker.js#383]
Hi.

I would like to add a QR code to my model. The QR Code is generated as a set of SVG paths with either fill:#ffffff or fill:#000000.

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ev="http://www.w3.org/2001/xml-events" width="270" height="270">
<path style="fill:#ffffff; stroke:none;" d="M0 0L0 270L270 270L270 0L0 0z"/>
<path style="fill:#000000; stroke:none;" d="M10 10L10 80L80 80L80 10L10 10M110 10L110 20L90 20L90 40L100 40L100 50L90 50L90 90L70 90L70 100L50 100L50 90L40 90L40 100L30 100L30 90L10 90L10 110L20 110L20 120L30 120L30 130L50 130L50 140L40 140L40 150L30 150L30 160L20 160L20 150L10 150L10 160L20 160L20 170L10 170L10 180L30 180L30 160L40 160L40 150L50 150L50 140L60 140L60 160L80 160L80 150L90 150L90 170L40 170L40 180L90 180L90 200L110 200L110 210L100 210L100 220L90 220L90 230L110 230L110 240L90 240L90 260L110 260L110 240L120 240L120 230L130 230L130 220L120 220L120 230L110 230L110 210L120 210L120 200L130 200L130 210L140 210L140 190L150 190L150 210L160 210L160 200L170 200L170 220L150 220L150 230L170 230L170 250L160 250L160 240L150 240L150 250L160 250L160 260L210 260L210 250L190 250L190 240L180 240L180 220L210 220L210 240L220 240L220 250L230 250L230 240L240 240L240 220L230 220L230 230L220 230L220 210L250 210L250 220L260 220L260 210L250 210L250 200L260 200L260 180L250 180L250 190L240 190L240 170L250 170L250 160L260 160L260 130L240 130L240 140L230 140L230 130L220 130L220 120L210 120L210 130L200 130L200 100L220 100L220 90L190 90L190 110L180 110L180 90L170 90L170 80L180 80L180 60L170 60L170 50L160 50L160 40L170 40L170 30L180 30L180 20L170 20L170 10L140 10L140 20L160 20L160 30L150 30L150 60L160 60L160 70L150 70L150 90L130 90L130 80L140 80L140 40L130 40L130 80L120 80L120 50L110 50L110 40L100 40L100 30L120 30L120 10L110 10M190 10L190 80L260 80L260 10L190 10z"/>
<path style="fill:#ffffff; stroke:none;" d="M20 20L20 70L70 70L70 20L20 20M200 20L200 70L250 70L250 20L200 20z"/>
<path style="fill:#000000; stroke:none;" d="M30 30L30 60L60 60L60 30L30 30M210 30L210 60L240 60L240 30L210 30z"/>
<path style="fill:#ffffff; stroke:none;" d="M100 60L100 90L90 90L90 100L110 100L110 110L100 110L100 120L120 120L120 90L110 90L110 60L100 60M160 70L160 80L170 80L170 70L160 70M150 90L150 100L140 100L140 120L150 120L150 130L130 130L130 170L100 170L100 180L110 180L110 200L120 200L120 190L130 190L130 170L150 170L150 180L160 180L160 190L170 190L170 180L160 180L160 170L180 170L180 160L200 160L200 170L220 170L220 160L230 160L230 170L240 170L240 160L250 160L250 140L240 140L240 160L230 160L230 150L220 150L220 130L210 130L210 150L220 150L220 160L200 160L200 150L180 150L180 140L190 140L190 130L180 130L180 140L150 140L150 130L160 130L160 120L180 120L180 110L170 110L170 90L150 90z"/>
<path style="fill:#000000; stroke:none;" d="M230 90L230 100L250 100L250 110L240 110L240 120L260 120L260 100L250 100L250 90L230 90z"/>
<path style="fill:#ffffff; stroke:none;" d="M20 100L20 110L30 110L30 100L20 100M70 100L70 110L80 110L80 100L70 100M50 110L50 130L60 130L60 140L70 140L70 150L80 150L80 140L90 140L90 150L100 150L100 160L120 160L120 140L110 140L110 130L100 130L100 140L90 140L90 130L80 130L80 120L70 120L70 130L60 130L60 110L50 110z"/>
<path style="fill:#000000; stroke:none;" d="M70 130L70 140L80 140L80 130L70 130M140 140L140 160L160 160L160 150L150 150L150 140L140 140M170 150L170 160L180 160L180 150L170 150z"/>
<path style="fill:#ffffff; stroke:none;" d="M180 180L180 210L210 210L210 180L180 180z"/>
<path style="fill:#000000; stroke:none;" d="M10 190L10 260L80 260L80 190L10 190M190 190L190 200L200 200L200 190L190 190z"/>
<path style="fill:#ffffff; stroke:none;" d="M220 190L220 200L240 200L240 190L220 190M20 200L20 250L70 250L70 200L20 200z"/>
<path style="fill:#000000; stroke:none;" d="M30 210L30 240L60 240L60 210L30 210M250 230L250 240L260 240L260 230L250 230M130 250L130 260L140 260L140 250L130 250M240 250L240 260L260 260L260 250L240 250z"/>
</svg>`

Thank you for the help.

Tshitshi

**Comment by danmarshall** [comment]
Hi @tkinte , please see #324 regarding an issue with DXF polylines which occupy the same point more than 2 times. Currently, this breaks the [chain finding algorithm](https://github.com/Microsoft/maker.js/issues/324#issuecomment-364597521). 

To make this work in a deterministic way, we will need 2 things:
1. Import SVG path data as a chain
2. Export chain to DXF

I'm going to close this issue and we can continue tracking in #324
