### ISSUE TITLE
Bezier curves with more than 4 points

### ISSUE THREAD

**Issue by DanDaHahn** [microsoft/maker.js#392]
I've got this Issue: I want to display a dxf in the Viewer. Right now I'am writing a parser for it. Now I've got problems with Splines (BezierCurves). As I noticed, only certain curves (quadratic and cubic ) are supported which have 3 or 4 points. However, I also have Splines that have more than 4 points. Would you have an idea to implement it anyways?
Best regards

**Comment by danmarshall** [comment]
I would start by looking here: https://math.stackexchange.com/questions/417859/convert-a-b-spline-into-bezier-curves
