### ISSUE TITLE
Can you load your own models into the playground?

### ISSUE THREAD

**Issue by timdiacon** [Microsoft/maker.js#396]
Is this possible? I can't see any documentation specifically about the playground but it's kind of exactly what I need

**Comment by danmarshall** [comment]
Yes there are a few ways - see [this comment](https://github.com/Microsoft/maker.js/issues/380#issuecomment-474065503).

**Comment by timdiacon** [comment]
Thanks Dan, it's point 4 I was hoping existed :-)

Thanks however for being so responsive and creating such an amazing library!
