### ISSUE TITLE
How to draw an arch with offset center of a circle?

### ISSUE THREAD

**Issue by doox911** [Microsoft/maker.js#399]
No problem to draw such an arch:
![Снимок экрана от 2019-04-23 23-20-11](https://user-images.githubusercontent.com/35161922/56613002-5ef9ec00-661e-11e9-8a58-621fe3ddb879.png)

But how to draw the offset circle in `maker`?

![Снимок экрана от 2019-04-23 23-15-09](https://user-images.githubusercontent.com/35161922/56612708-b0ee4200-661d-11e9-86c6-3276da11926b.png)

**Comment by danmarshall** [comment]
The easiest way may be to [create an arc from 3 points](https://maker.js.org/docs/api/classes/makerjs.paths.arc.html#constructor).

**Comment by danmarshall** [comment]
```
        /**
         * Class for arc path, created from 3 points.
         * 
         * @param pointA First end point of the arc.
         * @param pointB Middle point on the arc.
         * @param pointC Second end point of the arc.
         */
        constructor(pointA: IPoint, pointB: IPoint, pointC: IPoint);
```

**Comment by doox911** [comment]
I'm sorry, but I can't understand what is the center, what x and y (

**Comment by doox911** [comment]
Спасибо)
