### ISSUE TITLE
how to draw double line in makerjs?

### ISSUE THREAD

**Issue by Mrluobo** [Microsoft/maker.js#400]
Hi ,i am new to makerjs. we often use double line in autoCAD to means walls.I want to draw double line using makerjs and export cxf file. is there any easy way to draw double line in makerjs?

hope for you help   thx

**Comment by danmarshall** [comment]
Yes, you can use the [Wireframe technique](https://maker.js.org/docs/advanced-drawing/#Wireframe%20technique). First, make a single line drawing. Then, call [`makerjs.model.expandPaths`](https://maker.js.org/docs/api/modules/makerjs.model.html#expandpaths).
See [Expanding paths](https://maker.js.org/docs/advanced-drawing/#Expanding%20paths) for more info.

**Comment by Mrluobo** [comment]
it works well!   thank you so much
