### ISSUE TITLE
export a closed path to DXF

### ISSUE THREAD

**Issue by PodgPow** [microsoft/maker.js#401]
How do I export a closed path to DXF so that all lines are merged?
I tried through ConnectTheDots Class. - I did not succeed.
When viewed in AutoCAD, each individual is highlighted separately.
If you use usePOLYLINE: True, then the generated file is not readable by AutoCad

**Comment by PodgPow** [comment]
I found a solution (I had to change the library code)

**Comment by danmarshall** [comment]
Hi @PodgPow - Can you try again with the latest release 0.14.0 - I added a fix that makes POLYLINE work with my AutoCAD viewer at least.
