### ISSUE TITLE
Position the text

### ISSUE THREAD

**Issue by doox911** [microsoft/maker.js#408]
Good day. I can not understand how to position the text, for example with respect to the model?

**Comment by danmarshall** [comment]
Hello, sorry for the late response. I think my original reply may not have sent.

There are 2 forms of text in Maker.js. Do you mean [captions](https://maker.js.org/docs/intermediate-drawing/#Captions) or do you mean [fonts](https://maker.js.org/docs/advanced-drawing/#Fonts%20and%20text)?
