### ISSUE TITLE
Various Text Sizes for Captions

### ISSUE THREAD

**Issue by DerKorb** [microsoft/maker.js#422]
It would be very useful to specify the font size for captions on a per-caption basis instead of all captions having the same size.

**Comment by danmarshall** [comment]
Hi @DerKorb - thanks for the feature request. 

Looking at PR #419 - we will need a way of knowing what the caption size should be. I don't believe the current default of "9" is sufficient. Ideally we could have the ability for these 3 scenarios:

* change all captions to a specified size
* have various sizes
* smarter default size based on the drawing
