### ISSUE TITLE
gcode

### ISSUE THREAD

**Issue by ericLugtigheid** [microsoft/maker.js#423]
Has anyone ever tried or implemented GCODE as output for CNC routers?

**Comment by danmarshall** [comment]
Hi @ericLugtigheid , check out http://jscut.org/ or the [gcode topic on GitHub](https://github.com/topics/gcode)

**Comment by ericLugtigheid** [comment]
Hi Dan,
Thanks for your idea. I already checked jscut, very neat indeed but i would like to have a direct output in gcode.... I'll check out the topic on GitHub.

Eric

**Comment by danmarshall** [comment]
My personal experience with gcode has been with 3D printers. The first commands were machine-specific codes to initialize the machine. The next commands were to position the part relative to the machine’s working area. Finally the remaining commands were the actual part. But these moves also have optimizations. In 3D printing, overlap is ok and the main optimization is for time. With a CNC router however, you may have some z commands along the way which leave tabs that you later break away, so the part is held in place securely.
So the bottom line is, IMO, that the gcode is going to be very specific for a machine and a given scenario. You’d need to be able to tweak a lot of parameters to get your desired result.
Can you give any specific details about the gcode you seek? Is there some generic gcode “move commands” that you would find useful? How would you use the gcode?

**Comment by rmm5t** [comment]
> With a CNC router however, you may have some z commands along the way which leave tabs that you later break away, so the part is held in place securely.

To add to the complications of this, gcode must also take into consideration the kerf of the cut. e.g. the diameter of a router bit or even the kerf of a laser.

**Comment by msurguy** [comment]
@ericLugtigheid check out this project : https://github.com/makercam/openjscam

**Comment by danmarshall** [comment]
@ericLugtigheid - I just found a few more gcode projects:
* https://github.com/oneislandearth/gcode
* https://github.com/drandrewthomas/gcodercnc2d5

**Comment by danmarshall** [comment]
Also wanted to point out, from looking at this sample code at https://github.com/oneislandearth/gcode :
```
// Start the spindle
code.startSpindle();

// Start the coolant
code.startCoolant();

// Drop the mill to the bottom of the board
code.dropMill();

// Cut lengthways 65.5cm
code.feedLinear([0, 65.5]);
```
Operations such as `startSpindle` and `startCoolant` make me believe that gcode is out of scope for Maker.js - I'm going to close this issue. I hope you've found enough resources in the links above to make it work. Thanks, Dan
