### ISSUE TITLE
Feature Request - Nesting models across defined sheet size

### ISSUE THREAD

**Issue by timdiacon** [microsoft/maker.js#449]
This is a bit of a long shot but though I'd post to see if it would be of use to anyone else. Our current workflow is to use makerjs to create dxfs of the objects we are going to cut out on a cnc machine. We import the objects in vcarve and then nest and toolpath. If we could nest the objects in makerjs it would be amazing for 2 reasons.

- The nesting in vcarve isn't great
- If the objects were nested in makerjs we could calculate the exact sheet usage required right in the browser and know what to order without having to export and nest first

Appreciate this might be something of a niche use case, would be interesting to hear if anyone else would find this feature useful

**Comment by danmarshall** [comment]
Have you seen SVGnest? https://svgnest.com/
