### ISSUE TITLE
DXF export - Layer name max length

### ISSUE THREAD

**Issue by geolehmann** [microsoft/maker.js#456]
Hello everybody,

it seems there is a strange 30 character limit to to length of the DXF layer names. 
If I use the following:
```
var polyline= new makerjs.models.ConnectTheDots(false, points);
polyline.layer = "somelonglayernamewhichcontainsmorethanthirtycharacters"
var dxf = makerjs.exporter.toDXF(polyline);
```
the generated .dxf file can be imported without problems into AutoCAD.
However, I want to specifiy the color of the layer, so I add the code:

```
var options = {
        layerOptions: {
            "somelonglayernamewhichcontainsmorethanthirtycharacters": {
                color: 2
            }
};
var dxf = makerjs.exporter.toDXF(polyline,options);
```
Now AutoCAD fails to import the dxf file and tells me there is an invalid table entry on the line with the layer name. if I manually edit the dxf file and change the layer name back to a string with < 30 characters, the file can be imported without problems.

Is this a known issue? Are there any solutions for exporting layers with color definition and names with >30 characters? Thanks for help!

**Comment by danmarshall** [comment]
According to [this page](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/AutoCAD-Core/files/GUID-CE211679-F264-4128-BE00-BF4E0E7DEA8E-htm.html), a layer name can be up to 255 characters, but you may not use these characters: `< > / \ “ : ; ? * | = ‘` Also, see #432

**Comment by geolehmann** [comment]
Thanks for your reply, however, there arent any of these special characters in the layer name, only [a-z,A-Z].

**Comment by danmarshall** [comment]
How about in AutoCAD itself? Are you able to name layers with long names, export, then import again?

**Comment by ru1973** [comment]
DXF thru version R14 does not support long layer names, and will switch all lower case to UPPER case

**Comment by geolehmann** [comment]
Thanks @ru1973, this explains this strange behaviour. Seems like there is no way around this limitation :-(
