### ISSUE TITLE
TypeError: makerjs.model.addCaption is not a function (

### ISSUE THREAD

**Issue by icodk** [microsoft/maker.js#464]
Get the following error in an otherwise functioning vuejs and makerjs 
`vue.esm.js?efeb:628 [Vue warn]: Error in mounted hook: "TypeError: makerjs.model.addCaption is not a function"`
Had similar issue in the past   #352
Any idea?

**Comment by icodk** [comment]
I can do something like this with no error  but no text is shown
```

              mymodel.caption={
                  text: "This is a caption",
                  anchor: new makerjs.paths.Line([0, 50], [1000, 50])
              };
```

**Comment by danmarshall** [comment]
Are you using an older version of the library?

**Comment by icodk** [comment]
YES !! :-)
Sorry about that 
I use https://cdn.jsdelivr.net/npm/makerjs@0/target/js/browser.maker.js
Works fine with the new

**Comment by icodk** [comment]
But the caption text is not exported to DXF nor to PDF. Is opentype being exported ?

**Comment by icodk** [comment]
Sorry about that too
It works great in both PDF and DXF
