### ISSUE TITLE
How to get models in Text Wrapping example

### ISSUE THREAD

**Issue by mfadel85** [microsoft/maker.js#471]
Thanks everyone,

how can I get modes and generate svg in this [example ](https://maker.js.org/playground/?script=makerjs-wrap-text#params=[%22allertastencil-regular%22,%22Hello%20World!%20This%20box%20should%20start%20word-wrapping!%22,72,398,%22left%22,1.175])

I tried makerjs.exporter.toSVG() but didn't work
I tried to understand this code

```
 layout.glyphs.forEach((glyph, i) => {

        var character = makerjs.models.Text.glyphToModel(glyph.data, fontSize);

        character.origin = makerjs.point.scale(glyph.position, scale);

        makerjs.model.addModel(this, character, i);

      	console.log('this',this);
    });
```

by adding 
`console.log('this',this);`

printed nothing.
best regards

**Comment by danmarshall** [comment]
Hi @mfadel85, looks like our implementation of `console.log` does not handle multiple parameters. You might try:
```js
console.log("this");
console.log(this);
```

**Comment by mfadel85** [comment]
thanks @danmarshall 
it works
