### ISSUE TITLE
using toSVG() method can I set a margin for the generated SVG object?

### ISSUE THREAD

**Issue by mfadel85** [microsoft/maker.js#472]
Hello everyone,
using
var output = makerjs.exporter.toSVG(models);
can I set margins for the  generated svg object, for example 10mm, 5mm?

**Comment by danmarshall** [comment]
Can you try to pass an options object, and use the `origin` property?
```js
var output = makerjs.exporter.toSVG(models, { origin: [10, 10]});
```

**Comment by mfadel85** [comment]
thank you very much
