### ISSUE TITLE
Feature Request: Import svg file

### ISSUE THREAD

**Issue by Byteschmiede** [microsoft/maker.js#489]
Hello,

I would love to see the feature, that i can load a whole svg file into maker.js instead of just using raw svg path data.

Is there any chance to get this feature done or is it against the architecture?

**Comment by danmarshall** [comment]
Hello, please see #329 for some similar discussion. Also look at similar issues: https://github.com/microsoft/maker.js/issues?q=is%3Aissue+svg+import

The reason this feature does not exist is that there are too many assumptions that cannot be made. Remember that Maker.js is strictly line drawing, and does not have a "fill" concept. Also, SVG may contain fill patterns which repeat more SVG within a space. These any many other concepts are a superset of what Maker.js does, and so it is unknown how to handle the import. The expectation would vary for different applications.

Next, there are many ways to get SVG, such as in Node.js or in a browser environment. There are several XML parsers for Node, and the browser may or may not be able to obtain the SVG both as string or XML DOM. The import routine would need to know how to handle an SVG document, which again would not be the same for all applications. 

So I don't think a solution can generalize. If you can define your environment and application, and types of SVG you expect to handle, I can help to describe an approach.
