### ISSUE TITLE
toPdf() doesn't display the whole model content.

### ISSUE THREAD

**Issue by Sarthak0702** [microsoft/maker.js#528]
On exporting to pdf vis toPDF() complete model is not displayed on the one page pdf generated, with is zoom/cropped in.

 dxf pic (actual Model)
<img width="292" alt="image" src="https://user-images.githubusercontent.com/48375025/166821422-a5ab480c-739a-4159-a426-55c46059ff7b.png">

pdf pic (cropped Model)
![image](https://user-images.githubusercontent.com/48375025/166821846-207d82f8-0bdd-4770-810f-0733d9c2b024.png)

As you can see only this part of the actual model is displayed in the pdf
<img width="524" alt="image" src="https://user-images.githubusercontent.com/48375025/166821588-6d91d853-bfac-4083-947b-5e0f07b131c1.png">

Here is the `iModel` json that was exported: https://gist.github.com/Sarthak0702/640d5deecf363cae36f3ccadadeb626b

Code Used:
```js
exportToPDF(iModel: MakerJs.IModel){
  const doc: PDFKit.PDFDocument = new PDFDocument();
  const stream = doc.pipe(BlobStream());
  MakerJs.exporter.toPDF(
      doc, 
      iModel,
      {
        units: MakerJs.unitType.Millimeter
      }
  );
  doc.end();
  return stream;
}
```

**Comment by danmarshall** [comment]
Hello, I think it's a scale issue. I was able to fit on one page by:

```js
var makerjs = require('makerjs');

var models = your_json;

var x = { models: models, units:'mm' };
makerjs.model.scale(x, 0.1)
module.exports = x;
```

![image](https://user-images.githubusercontent.com/11507384/166831449-55fec754-6c24-42b5-ba40-df07ed50007d.png)


Without scaling, the model appears as:
![image](https://user-images.githubusercontent.com/11507384/166831121-b41ca5b2-f55c-4c2d-80b5-3943047d1bee.png)

Each grid square is 100mm. A PDF page is about 216mm wide, so without scaling your model would take up about 10 pages wide.

**Comment by Sarthak0702** [comment]
Thanks for this. I assumed that the exporter would automatically scale the content to fit it in one page. This dynamic scaling worked for me.

```js
let size = MakerJs.measure.modelExtents(iModel);
let xScale=size.width/216;
let yScale=size.height/280;
let scale=Math.max(xScale,yScale);
doc.scale(scale);
```

**Comment by danmarshall** [comment]
No problem. The exporter doesn't automatically scale so that you can create a PDF in the exact coordinate space, for example if you are creating a ruler.

**Comment by Sarthak0702** [comment]
Makes sense!. Closing issue :).
