### ISSUE TITLE
childrenOnPath giving Nan

### ISSUE THREAD

**Issue by noobd3v** [microsoft/maker.js#550]
Hi I was trying to generate children on path with following data. But its not working and giving nan svg paths.
```

 var rect = new makerjs.models.Rectangle(1, 1)
    var arc = new makerjs.paths.Arc([13.331144128254737, 3.140174147778744], 7.0420346849616, 103.3236939533026, 104.25739656359501);
	var row = makerjs.layout.cloneToRow(rect, 1);
    makerjs.layout.childrenOnPath(row, arc, 0.5, false, false, true);

    this.models = {
        topText: row
    };

```

<img width="951" alt="image" src="https://user-images.githubusercontent.com/13329441/214245899-88668fa7-5574-4e24-8196-128027a264c5.png">

**Comment by danmarshall** [comment]
Hi @noobd3v would you mind pasting the entire code? Thanks!

**Comment by danmarshall** [comment]
Thank you very much for the code sample, it was helpful for the repro.
Looks like there is a guard missing for division by zero:

https://github.com/microsoft/maker.js/blob/master/packages/maker.js/src/core/layout.ts#L64-L66

This happens in a degenerate case when calling `layout.cloneTo...` with 1 as the count. Also, the core code should have a guard for the special case when count is <= 1. 

As a workaround for now, can you ensure your calling code only calls layout with a count > 1?
One more thing, probably good to pass a margin too:
```js
var row = makerjs.layout.cloneToRow(rect, 1);  //count is 1, no margin
```
