### ISSUE TITLE
The byLayers option is not working properly in findChains

### ISSUE THREAD

**Issue by techa** [microsoft/maker.js#562]
Setting the layer name to the model does not work because the layer name is taken from the path [here](https://github.com/microsoft/maker.js/blob/master/packages/maker.js/src/core/chain.ts#L169).

Alternative solution.
- Use `model.layer()` to reflect layer names on child models and paths as well.

**Comment by danmarshall** [comment]
A layer on a path will override a layer on the containing model.

**Comment by techa** [comment]
Sorry, I tried it with a simple code and you were right.

However, with my code, this does not work as expected.
```
model.layer = 'layer-name';
```

If I use a function that overwrites the layer name to lower paths, it works as expected.

There must be something else causing this. I will try to find it.
Thanks for the reply.

**Comment by techa** [comment]
It was caused by layer names remaining in the child models of the model created by compositing with `model.combine()`.
