### ISSUE TITLE
How can the relative coordinates of all the text paths in the rectangles be obtained in makerjs?

### ISSUE THREAD

**Issue by PPDEMOone** [microsoft/maker.js#581]
How can the relative coordinates of all the text paths in the rectangles be obtained in makerjs?

1. Firstly I use the (makerJs.importer.fromSVGPathData) method and create the path, and  I got the textModelnstance from the (makerJs.models.Text)
2. Then I moved the origin of both model objects to [0,0] with (makerjs.model.zero)
3. I use the (makerjs.model.walkPath) to get  all the path origin in the textModelnstance

But the  textModelnstance have some Bessel curves and paths, I'm not sure which parameters I want in (makerjs.model.walkPath) method result

<img width="1780" alt="image" src="https://github.com/microsoft/maker.js/assets/64009332/876b480f-0f0f-47b2-9dc9-3377ea22de32">

This is my code 

```typescript
const textModel = await createTextModel();

const bottomModel = makerJs.importer.fromSVGPathData(
  "M0,0V21.09A2.83,2.83,0,0,1,.86,25a2.72,2.72,0,0,1-.86.86v2.48H5.67V0ZM2.83,7.8A2.13,2.13,0,1,1,5,5.67,2.13,2.13,0,0,1,2.83,7.8Z"
);

const measureRect: makerJs.IModel = new makerJs.models.Rectangle(269.29, 93.54);

const { center: measureRectCenter, high: measureRectHigh } =
  makerJs.measure.modelExtents(measureRect);

makerJs.model.zero(measureRect);
makerJs.model.zero(bottomModel);
makerJs.model.zero(textModel);

const { width: textWidth, height: textHeight } =
  makerJs.measure.modelExtents(textModel);

makerJs.model.moveRelative(bottomModel, [measureRectCenter[0], 0]);
makerJs.model.moveRelative(textModel, [
  measureRectCenter[0] - textWidth / 2,
  measureRectCenter[1] - textHeight / 2,
]);

// console.log(transformOrigin);

const { high: measureBottomHigh, width: measureBottomModel } =
  makerJs.measure.modelExtents(bottomModel);

const bModelTopEndPointLeft = bottomModel.origin,
  bModelTopEndPointRight = [
    bottomModel.origin![0] + measureBottomModel,
    bottomModel.origin![1],
  ] as makerJs.IPoint;

// console.log(makerJs.measure.modelExtents(bottomModel));

makerJs.model.walkPaths(textModel, (val) => {
  if (val.type === "BezierCurve") {
    const bezierCurvePath = val as InstanceType<
      typeof makerJs.models.BezierCurve
    >;
    console.log(bezierCurvePath);
  } else {
    // console.log(val.origin);
  }
});

const model: IModel = {
  models: {
    bc3: bottomModel,
    text: textModel,
    measure: measureRect,
    ref_line_1: createDashedLine([0, 0], bModelTopEndPointRight!, 5),
    ref_line_2: createDashedLine([0, 0], bModelTopEndPointLeft!, 5),
    ref_middle_line: createDashedLine(
      [0, measureRectCenter[1]],
      [measureRectHigh[0], measureRectCenter[1]],
      5
    ),
    ref_bottom_line: createDashedLine(
      [0, measureBottomHigh[1]],
      [measureRectHigh[0], measureBottomHigh[1]],
      5
    ),
  },
};
```

**Comment by PPDEMOone** [comment]
I just found this method （makerJs.model.originate） seems to solve my problem

```typescript
const model: IModel = {
  models: {
    bc3: bottomModel,
    text: textModel,
    measure: measureRect,
    ref_line_1: createDashedLine([0, 0], bModelTopEndPointRight!, 5),
    ref_line_2: createDashedLine([0, 0], bModelTopEndPointLeft!, 5),
    ref_middle_line: createDashedLine(
      [0, measureRectCenter[1]],
      [measureRectHigh[0], measureRectCenter[1]],
      5
    ),
    ref_bottom_line: createDashedLine(
      [0, measureBottomHigh[1]],
      [measureRectHigh[0], measureBottomHigh[1]],
      5
    ),
  },
  paths: {
    line: new makerJs.paths.Line([0, 0], [202.3195951860165, 81.1357899049327]),
  },
};

makerJs.model.originate(model);

makerJs.model.walkPaths(textModel, (val) => {
  if (val.type === "BezierCurve") {
    const bezierCurvePath = val as InstanceType<
      typeof makerJs.models.BezierCurve
    >;
    console.log(bezierCurvePath);
  } else {
    // console.log(val.origin);
  }
});
``` 

<img width="1897" alt="image" src="https://github.com/microsoft/maker.js/assets/64009332/4b120821-02b5-4a03-90b1-3d6e61a5db2e">

**Comment by PPDEMOone** [comment]
> I just found this method(makerJs.model.originate)seems to solve my problem
> 
> ```ts
> const model: IModel = {
>   models: {
>     bc3: bottomModel,
>     text: textModel,
>     measure: measureRect,
>     ref_line_1: createDashedLine([0, 0], bModelTopEndPointRight!, 5),
>     ref_line_2: createDashedLine([0, 0], bModelTopEndPointLeft!, 5),
>     ref_middle_line: createDashedLine(
>       [0, measureRectCenter[1]],
>       [measureRectHigh[0], measureRectCenter[1]],
>       5
>     ),
>     ref_bottom_line: createDashedLine(
>       [0, measureBottomHigh[1]],
>       [measureRectHigh[0], measureBottomHigh[1]],
>       5
>     ),
>   },
>   paths: {
>     line: new makerJs.paths.Line([0, 0], [202.3195951860165, 81.1357899049327]),
>   },
> };
> 
> makerJs.model.originate(model);
> 
> makerJs.model.walkPaths(textModel, (val) => {
>   if (val.type === "BezierCurve") {
>     const bezierCurvePath = val as InstanceType<
>       typeof makerJs.models.BezierCurve
>     >;
>     console.log(bezierCurvePath);
>   } else {
>     // console.log(val.origin);
>   }
> });
> ```
> 
> <img alt="image" width="1897" src="https://user-images.githubusercontent.com/64009332/282676480-4b120821-02b5-4a03-90b1-3d6e61a5db2e.png">

**Comment by danmarshall** [comment]
Thanks for the question. For anyone else who wants to know more please see [originating](https://maker.js.org/docs/intermediate-drawing/#Originating) in the documentation.
