### ISSUE TITLE
How can I get the text in the exported DXF file to be filled in color or have just 1 stroke line? Please help me solve it.

### ISSUE THREAD

**Issue by phong-hopee** [microsoft/maker.js#599]
![Verb 1234](https://github.com/user-attachments/assets/371deecd-4156-4a2b-b1f4-7cfa83af4fc3)
SVG file

![Screen Shot 2024-07-26 at 16 33 07](https://github.com/user-attachments/assets/63e1dda3-ed46-475a-b2f8-322eef90105f)
DXF after export

**Comment by danmarshall** [comment]
Hello, is this a variable font? We currently don't have a solution for the overlap issue. Also see discussion at https://github.com/danmarshall/google-font-to-svg-path/issues/40
