### ISSUE TITLE
Path showing endless false whether as per points it is closed path

### ISSUE THREAD

**Issue by Gautam2010** [microsoft/maker.js#603]
Path is endless as per attached image.
![image](https://github.com/user-attachments/assets/241925c4-5c9b-4afb-8507-c4605f1e6153)

while converting `model `and `chain `it is showing `endless=false
`

`M721 209.62a99.596 99.596 0 0 0 12.013-18.008c7.611-14.863 11.422-29.726 11.422-44.6 0-30.807-10.793-54.558-32.365-71.242-21.576-16.679-53.757-25.018-96.535-25.018H455.637 V55.1 c5.8 4.354 10.334 11.416 13.596 21.212 3.267 9.78 4.898 23.208 4.898 40.245v243.645 c0 17.048-1.636 30.375-4.898 39.97-3.262 9.617-7.795 16.78-13.596 21.492v4.344 h191.434 c44.24 0 77.957-9.965 101.17-29.916 23.196-19.935 34.803-48.948 34.803-87.013 0-26.464-7.706-49.218-23.118-68.261-10.007-12.361-23.017-22.748-38.92-31.209`

**Comment by danmarshall** [comment]
In the [svgPathEditor](https://yqnn.github.io/svg-path-editor/#P=M_721_209.62_a_99.596_99.596_0_0_0_12.013_-18.008_c_7.611_-14.863_11.422_-29.726_11.422_-44.6_c_0_-30.807_-10.793_-54.558_-32.365_-71.242_c_-21.576_-16.679_-53.757_-25.018_-96.535_-25.018_H_455.637_V_55.1_c_5.8_4.354_10.334_11.416_13.596_21.212_c_3.267_9.78_4.898_23.208_4.898_40.245_v_243.645_c_0_17.048_-1.636_30.375_-4.898_39.97_c_-3.262_9.617_-7.795_16.78_-13.596_21.492_v_4.344_h_191.434_c_44.24_0_77.957_-9.965_101.17_-29.916_c_23.196_-19.935_34.803_-48.948_34.803_-87.013_c_0_-26.464_-7.706_-49.218_-23.118_-68.261_C_749.919_228.457_736.909_218.07_721.006_209.609), I converted the last point to absolute:
<img width="220" alt="image" src="https://github.com/user-attachments/assets/38b051c1-dd05-4dbb-a57f-5b48aa9bc139">
So you can see the first and last point are not exactly the same by a small degree.
