### ISSUE TITLE
PDF Export?

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/maker.js#88]
This may be a great feature for creating paper-based models. Not sure if there is any community interest for this.

**Comment by NickNaso** [comment]
Yes it could be a good feature

**Comment by zrichmond** [comment]
I'd definitely make use of pdf export. There are svg to pdf tools out there, however built-in capability would simplify things on the user end and that's usually a good thing.

**Comment by gPrio** [comment]
Yes it would be great, but please note it is important to include Color names and Layers information in PDF.

**Comment by danmarshall** [comment]
added in 0.8.0 - this is a basic implementation, and I'm sure there could be a lot of feature additions to PDF customization.
