### ISSUE TITLE
SVG Export as continuous path?

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/maker.js#97]
Another feature, I would like to hear from the community if it would be useful.
Currently all paths are "standalone" - however SVG has the continuous path. This would allow one to use a fill, although in MakerJs there are only lines and no fill.

**Comment by tonillo** [comment]
yes it could be a great feature!

**Comment by zrichmond** [comment]
I also like to see this, but maybe as a more general concept. Potentially where there would be a way to group paths selectively based on how the user specifies.  Then when exporting, the grouping appropriate for the file format is handled in the file format specific way.

**Comment by danmarshall** [comment]
added in 0.8.0
